# Generated by Django 5.2.12 on 2026-04-02 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, default='', max_length=120)),
                ('facts', models.JSONField(blank=True, default=list)),
                ('recent_emotions', models.JSONField(blank=True, default=list)),
                ('user_message_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User chat memories',
            },
        ),
    ]
