# Generated by Django 5.2.12 on 2026-04-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user_chat_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='agent_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='conversation',
            name='agent_relationship_stage',
            field=models.CharField(choices=[('stranger', 'Stranger'), ('acquaintance', 'Acquaintance'), ('trusted', 'Trusted'), ('close', 'Close')], default='stranger', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='empathy_effectiveness',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_satisfaction',
            field=models.FloatField(default=0.5),
        ),
    ]
